title: 29th Infantry Division
description: >- # this means to ignore newlines until next key
  The 29th Infantry Division is a realism unit spread throughout multiple games
  in multiple time periods. Each game is supported separately by different
  companies while serving under the same Battalion so that all games and soldiers
  function individually and as all whole.
default_hero_image: /assets/images/hero.png
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

menus:
  navbar:
    - text: Home
      link: /
    - text: About
      link: /about
    - text: Roster
      link: http://personnel.29th.org
    - text: Forum
      link: http://forums.29th.org
    - text: Enlist
      link: /enlist
  about:
    - text: Introduction
      link: /about
    - text: What is realism
      link: /about/realism
    - text: Training system
      link: /about/training

# Build settings
plugins:
  - jekyll-feed
